# Generated by Django 3.2.5 on 2021-07-29 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytuł', models.CharField(max_length=40)),
                ('autor', models.CharField(max_length=30)),
                ('data_publikacji', models.DateField()),
                ('numer_isbn', models.CharField(max_length=20)),
                ('liczba_stron', models.IntegerField(default=0)),
                ('link_do_okładki', models.TextField()),
                ('język_publikacji', models.CharField(max_length=20)),
            ],
        ),
    ]
