# Generated by Django 3.2.5 on 2021-07-29 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_link_do_okładki'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='data_publikacji',
            field=models.DateField(help_text='yyyy-mm-dd'),
        ),
        migrations.AlterField(
            model_name='book',
            name='numer_isbn',
            field=models.BigIntegerField(help_text='numer powinien składać się z 10 lub 13 cyfr', max_length=13),
        ),
    ]
