# Generated by Django 3.2.5 on 2021-07-30 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_book_numer_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='numer_isbn',
            field=models.CharField(help_text='numer powinien składać się z 10 lub 13 cyfr', max_length=20),
        ),
    ]
