# Generated by Django 3.2.5 on 2021-08-01 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_alter_book_numer_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='numer_isbn',
            field=models.CharField(max_length=20, verbose_name='Numer ISBN'),
        ),
    ]
