# Generated by Django 3.2.6 on 2021-08-13 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_alter_book_numer_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='liczba_stron',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
