# Generated by Django 3.2.6 on 2021-11-22 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_alter_autor_nazwisko'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='nazwisko',
            field=models.CharField(max_length=30, verbose_name='Autor'),
        ),
    ]
