# Generated by Django 3.2.6 on 2022-01-03 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_alter_autor_nazwisko'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='nazwisko',
            field=models.CharField(max_length=250, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='book',
            name='numer_isbn',
            field=models.CharField(max_length=50, verbose_name='Numer ISBN'),
        ),
        migrations.AlterField(
            model_name='book',
            name='tytuł',
            field=models.CharField(max_length=250),
        ),
    ]
